[Unit]
# LINSTOR must stay up while xapi-domains stops VMs down. Since systemd stops
# units in the reverse of their start order, we want LINSTOR to start first so
# that it stops last, which means xapi-domains has to be ordered After the LINSTOR
# units.
After=linstor-controller.service linstor-satellite.service
